config:
  database:
    url: jdbc:mysql://localhost/database?verifyServerCertificate=false&useSSL=true
    user: user
    password: password
    pool_size: 20
  lang:
    protection:
      nearby_blocks: "&cProtected block nearby"
      nearby_blocks_owned_by: "&cProtected block by &4{PLAYER}&c nearby"
      block_under_minimum_height: "&cUnder protected height"
      unprotected_world: "&cUnprotected world"
      unprotected_material_placed: "&cMaterial can't be protected"
      database_insert_failure: "&4Database failure on protection"
      debug:
        no_block: "&dDebug: &cthere is no block"
        debug_text: "&dDebug: &a%1$s valid=%4$b date=%2$s temporary=%3$b"
        database_failure: "&dDebug: &4database error"
        debug_list:
          title: "&dDebug: &6Protected blocks nearby %s&6:"
          text: "&dDebug: &3%1$s"
          empty: "&dDebug: &6No protected blocks nearby."
    friends:
      cant_be_console: "&cCan't be executed by console"
      no_friends: "&6You didn't add any friends! Try it: &a/addfriend <name of friend>"
      database_failure: "&cDatabase failure! Can't list your friends :("
      friend_not_found: "&4%s &cnot found on the server"
      friend_list:
        list_init: "&6Friends: "
        list_item: "&a%s&6, "
        unknown_name: "&cunknown&6, "
        has_not_played: "&4* &cHas not played before (probably a typo)"
      friend_add:
        command_help: "&6To add a friend, type &a/addfriend <name of friend>&6"
        friend_added: "&a%s &6was added as a friend!"
        already_friends: "&a%s &6is already your friend!"
        friend_can_not_be_you: "&cFriend can not be you"
      friend_delete:
        command_help: "&6To delete a friend, type &a/delfriend <name of friend>&6"
        friend_deleted: "&4%s &cremoved from your friend list!"
        deleted_all: "&6Deleted all friends!"
  protection:
    protected_for_days: 10
    minimum_height_to_protect: 36
    # Radius to protect against break, place and interact
    # Break: must be less or equal to half place radius
    protection_break_radius: 7
    protection_place_radius: 14
    # Interact: must be less than break radius
    protection_interact_radius: 6
    # Radius to update protection time for old blocks
    protection_update_time_radius: 14
    # Search for temporary blocks radius
    protection_search_radius: 5
    # Amount of temporary blocks to update as protected block
    protection_block_count: 26
    protected_worlds:
      - world
    materials:
      debug_item: STICK
      denied_interaction:
        - IRON_DOOR
        - HEAVY_WEIGHTED_PRESSURE_PLATE
        - LIGHT_WEIGHTED_PRESSURE_PLATE
        - POLISHED_BLACKSTONE_PRESSURE_PLATE
        - STONE_PRESSURE_PLATE
        - POLISHED_BLACKSTONE_BUTTON
        - STONE_BUTTON
        - LEVER
        - IRON_TRAPDOOR
        - ACACIA_FENCE_GATE
        - BIRCH_FENCE_GATE
        - CRIMSON_FENCE_GATE
        - DARK_OAK_FENCE_GATE
        - JUNGLE_FENCE_GATE
        - NETHER_BRICK_FENCE
        - OAK_FENCE_GATE
        - SPRUCE_FENCE_GATE
        - WARPED_FENCE_GATE
      protected_materials:
        - ACACIA_LOG
        - ACACIA_PLANKS
        - ACACIA_WOOD
        - ANDESITE
        - ANDESITE_WALL
        - BASALT
        - BIRCH_LOG
        - BIRCH_PLANKS
        - BIRCH_WOOD
        - BLACKSTONE
        - BLACKSTONE_WALL
        - BLACK_CONCRETE
        - BLACK_GLAZED_TERRACOTTA
        - BLACK_STAINED_GLASS
        - BLACK_STAINED_GLASS_PANE
        - BLACK_TERRACOTTA
        - BLACK_WOOL
        - BLAST_FURNACE
        - BLUE_CONCRETE
        - BLUE_GLAZED_TERRACOTTA
        - BLUE_STAINED_GLASS
        - BLUE_STAINED_GLASS_PANE
        - BLUE_TERRACOTTA
        - BLUE_WOOL
        - BONE_BLOCK
        - BOOKSHELF
        - BRICKS
        - BRICK_WALL
        - BROWN_CONCRETE
        - BROWN_GLAZED_TERRACOTTA
        - BROWN_MUSHROOM_BLOCK
        - BROWN_STAINED_GLASS
        - BROWN_STAINED_GLASS_PANE
        - BROWN_TERRACOTTA
        - BROWN_WOOL
        - CHISELED_NETHER_BRICKS
        - CHISELED_POLISHED_BLACKSTONE
        - CHISELED_QUARTZ_BLOCK
        - CHISELED_RED_SANDSTONE
        - CHISELED_SANDSTONE
        - CHISELED_STONE_BRICKS
        - COAL_BLOCK
        - COBBLESTONE
        - COBBLESTONE_WALL
        - CRACKED_NETHER_BRICKS
        - CRACKED_POLISHED_BLACKSTONE_BRICKS
        - CRACKED_STONE_BRICKS
        - CRIMSON_PLANKS
        - CUT_RED_SANDSTONE
        - CUT_SANDSTONE
        - CYAN_CONCRETE
        - CYAN_GLAZED_TERRACOTTA
        - CYAN_STAINED_GLASS
        - CYAN_STAINED_GLASS_PANE
        - CYAN_TERRACOTTA
        - CYAN_WOOL
        - DARK_OAK_LOG
        - DARK_OAK_PLANKS
        - DARK_OAK_WOOD
        - DARK_PRISMARINE
        - DIAMOND_BLOCK
        - DIORITE
        - DIORITE_WALL
        - EMERALD_BLOCK
        - END_STONE
        - END_STONE_BRICKS
        - END_STONE_BRICK_WALL
        - GLASS
        - GLASS_PANE
        - GLOWSTONE
        - GOLD_BLOCK
        - GRANITE
        - GRANITE_WALL
        - GRAY_CONCRETE
        - GRAY_GLAZED_TERRACOTTA
        - GRAY_STAINED_GLASS
        - GRAY_STAINED_GLASS_PANE
        - GRAY_TERRACOTTA
        - GRAY_WOOL
        - GREEN_CONCRETE
        - GREEN_GLAZED_TERRACOTTA
        - GREEN_STAINED_GLASS
        - GREEN_STAINED_GLASS_PANE
        - GREEN_TERRACOTTA
        - GREEN_WOOL
        - IRON_BLOCK
        - JUNGLE_LOG
        - JUNGLE_PLANKS
        - JUNGLE_WOOD
        - LAPIS_BLOCK
        - LIGHT_BLUE_CONCRETE
        - LIGHT_BLUE_GLAZED_TERRACOTTA
        - LIGHT_BLUE_STAINED_GLASS
        - LIGHT_BLUE_STAINED_GLASS_PANE
        - LIGHT_BLUE_TERRACOTTA
        - LIGHT_BLUE_WOOL
        - LIGHT_GRAY_CONCRETE
        - LIGHT_GRAY_GLAZED_TERRACOTTA
        - LIGHT_GRAY_STAINED_GLASS
        - LIGHT_GRAY_STAINED_GLASS_PANE
        - LIGHT_GRAY_TERRACOTTA
        - LIGHT_GRAY_WOOL
        - LIME_CONCRETE
        - LIME_GLAZED_TERRACOTTA
        - LIME_STAINED_GLASS
        - LIME_STAINED_GLASS_PANE
        - LIME_TERRACOTTA
        - LIME_WOOL
        - MAGENTA_CONCRETE
        - MAGENTA_GLAZED_TERRACOTTA
        - MAGENTA_STAINED_GLASS
        - MAGENTA_STAINED_GLASS_PANE
        - MAGENTA_TERRACOTTA
        - MAGENTA_WOOL
        - MAGMA_BLOCK
        - MOSSY_COBBLESTONE
        - MOSSY_COBBLESTONE_WALL
        - MOSSY_STONE_BRICKS
        - MOSSY_STONE_BRICK_WALL
        - MYCELIUM
        - NETHERITE_BLOCK
        - NETHERRACK
        - NETHER_BRICKS
        - NETHER_BRICK_WALL
        - NETHER_WART_BLOCK
        - OAK_LOG
        - OAK_PLANKS
        - OAK_WOOD
        - OBSIDIAN
        - ORANGE_CONCRETE
        - ORANGE_GLAZED_TERRACOTTA
        - ORANGE_STAINED_GLASS
        - ORANGE_STAINED_GLASS_PANE
        - ORANGE_TERRACOTTA
        - ORANGE_WOOL
        - PINK_CONCRETE
        - PINK_GLAZED_TERRACOTTA
        - PINK_STAINED_GLASS
        - PINK_STAINED_GLASS_PANE
        - PINK_TERRACOTTA
        - PINK_WOOL
        - POLISHED_ANDESITE
        - POLISHED_BASALT
        - POLISHED_BLACKSTONE
        - POLISHED_BLACKSTONE_BRICKS
        - POLISHED_BLACKSTONE_BRICK_WALL
        - POLISHED_BLACKSTONE_WALL
        - POLISHED_DIORITE
        - POLISHED_GRANITE
        - PRISMARINE
        - PRISMARINE_BRICKS
        - PRISMARINE_WALL
        - PURPLE_CONCRETE
        - PURPLE_GLAZED_TERRACOTTA
        - PURPLE_STAINED_GLASS
        - PURPLE_STAINED_GLASS_PANE
        - PURPLE_TERRACOTTA
        - PURPLE_WOOL
        - PURPUR_BLOCK
        - PURPUR_PILLAR
        - QUARTZ_BLOCK
        - QUARTZ_BRICKS
        - QUARTZ_PILLAR
        - REDSTONE_BLOCK
        - REDSTONE_LAMP
        - RED_CONCRETE
        - RED_GLAZED_TERRACOTTA
        - RED_MUSHROOM_BLOCK
        - RED_NETHER_BRICKS
        - RED_NETHER_BRICK_WALL
        - RED_SAND
        - RED_SANDSTONE
        - RED_SANDSTONE_WALL
        - RED_STAINED_GLASS
        - RED_STAINED_GLASS_PANE
        - RED_TERRACOTTA
        - RED_WOOL
        - SANDSTONE
        - SANDSTONE_WALL
        - SMOOTH_QUARTZ
        - SMOOTH_RED_SANDSTONE
        - SMOOTH_SANDSTONE
        - SMOOTH_STONE
        - SOUL_LANTERN
        - SOUL_SAND
        - SOUL_SOIL
        - SPRUCE_LOG
        - SPRUCE_PLANKS
        - SPRUCE_WOOD
        - STONE
        - STONECUTTER
        - STONE_BRICKS
        - STONE_BRICK_WALL
        - STRIPPED_ACACIA_LOG
        - STRIPPED_ACACIA_WOOD
        - STRIPPED_BIRCH_LOG
        - STRIPPED_BIRCH_WOOD
        - STRIPPED_CRIMSON_HYPHAE
        - STRIPPED_DARK_OAK_LOG
        - STRIPPED_DARK_OAK_WOOD
        - STRIPPED_JUNGLE_LOG
        - STRIPPED_JUNGLE_WOOD
        - STRIPPED_OAK_LOG
        - STRIPPED_OAK_WOOD
        - STRIPPED_SPRUCE_LOG
        - STRIPPED_SPRUCE_WOOD
        - STRIPPED_WARPED_HYPHAE
        - TERRACOTTA
        - WARPED_NYLIUM
        - WARPED_PLANKS
        - WARPED_WART_BLOCK
        - WHITE_CONCRETE
        - WHITE_GLAZED_TERRACOTTA
        - WHITE_STAINED_GLASS
        - WHITE_STAINED_GLASS_PANE
        - WHITE_TERRACOTTA
        - WHITE_WOOL
        - YELLOW_CONCRETE
        - YELLOW_GLAZED_TERRACOTTA
        - YELLOW_STAINED_GLASS
        - YELLOW_STAINED_GLASS_PANE
        - YELLOW_TERRACOTTA
        - YELLOW_WOOL
        - STRIPPED_ACACIA_LOG
        - STRIPPED_ACACIA_WOOD
        - STRIPPED_BIRCH_LOG
        - STRIPPED_BIRCH_WOOD
        - STRIPPED_CRIMSON_HYPHAE
        - STRIPPED_CRIMSON_STEM
        - STRIPPED_DARK_OAK_LOG
        - STRIPPED_DARK_OAK_WOOD
        - STRIPPED_JUNGLE_LOG
        - STRIPPED_JUNGLE_WOOD
        - STRIPPED_OAK_LOG
        - STRIPPED_OAK_WOOD
        - STRIPPED_SPRUCE_LOG
        - STRIPPED_SPRUCE_WOOD
        - STRIPPED_WARPED_HYPHAE
        - STRIPPED_WARPED_STEM
        - STRIPPED_ACACIA_LOG
        - STRIPPED_ACACIA_WOOD
        - STRIPPED_BIRCH_LOG
        - STRIPPED_BIRCH_WOOD
        - STRIPPED_CRIMSON_HYPHAE
        - STRIPPED_CRIMSON_STEM
        - STRIPPED_DARK_OAK_LOG
        - STRIPPED_DARK_OAK_WOOD
        - STRIPPED_JUNGLE_LOG
        - STRIPPED_JUNGLE_WOOD
        - STRIPPED_OAK_LOG
        - STRIPPED_OAK_WOOD
        - STRIPPED_SPRUCE_LOG
        - STRIPPED_SPRUCE_WOOD
        - STRIPPED_WARPED_HYPHAE
        - STRIPPED_WARPED_STEM
        - ACACIA_SLAB
        - ANDESITE_SLAB
        - BIRCH_SLAB
        - BLACKSTONE_SLAB
        - BRICK_SLAB
        - COBBLESTONE_SLAB
        - CRIMSON_SLAB
        - CUT_RED_SANDSTONE_SLAB
        - CUT_SANDSTONE_SLAB
        - DARK_OAK_SLAB
        - DARK_PRISMARINE_SLAB
        - DIORITE_SLAB
        - END_STONE_BRICK_SLAB
        - GRANITE_SLAB
        - JUNGLE_SLAB
        - MOSSY_COBBLESTONE_SLAB
        - MOSSY_STONE_BRICK_SLAB
        - NETHER_BRICK_SLAB
        - OAK_SLAB
        - PETRIFIED_OAK_SLAB
        - POLISHED_ANDESITE_SLAB
        - POLISHED_BLACKSTONE_BRICK_SLAB
        - POLISHED_BLACKSTONE_SLAB
        - POLISHED_DIORITE_SLAB
        - POLISHED_GRANITE_SLAB
        - PRISMARINE_BRICK_SLAB
        - PRISMARINE_SLAB
        - PURPUR_SLAB
        - QUARTZ_SLAB
        - RED_NETHER_BRICK_SLAB
        - RED_SANDSTONE_SLAB
        - SANDSTONE_SLAB
        - SMOOTH_QUARTZ_SLAB
        - SMOOTH_RED_SANDSTONE_SLAB
        - SMOOTH_SANDSTONE_SLAB
        - SMOOTH_STONE_SLAB
        - SPRUCE_SLAB
        - STONE_BRICK_SLAB
        - STONE_SLAB
        - WARPED_SLAB
        - ACACIA_FENCE
        - BIRCH_FENCE
        - CRIMSON_FENCE
        - DARK_OAK_FENCE
        - JUNGLE_FENCE
        - NETHER_BRICK_FENCE
        - OAK_FENCE
        - SPRUCE_FENCE
        - WARPED_FENCE
        - ACACIA_STAIRS
        - ANDESITE_STAIRS
        - BIRCH_STAIRS
        - BLACKSTONE_STAIRS
        - BRICK_STAIRS
        - COBBLESTONE_STAIRS
        - CRIMSON_STAIRS
        - DARK_OAK_STAIRS
        - DARK_PRISMARINE_STAIRS
        - DIORITE_STAIRS
        - END_STONE_BRICK_STAIRS
        - GRANITE_STAIRS
        - JUNGLE_STAIRS
        - MOSSY_COBBLESTONE_STAIRS
        - MOSSY_STONE_BRICK_STAIRS
        - NETHER_BRICK_STAIRS
        - OAK_STAIRS
        - POLISHED_ANDESITE_STAIRS
        - POLISHED_BLACKSTONE_BRICK_STAIRS
        - POLISHED_BLACKSTONE_STAIRS
        - POLISHED_DIORITE_STAIRS
        - POLISHED_GRANITE_STAIRS
        - PRISMARINE_BRICK_STAIRS
        - PRISMARINE_STAIRS
        - PURPUR_STAIRS
        - QUARTZ_STAIRS
        - RED_NETHER_BRICK_STAIRS
        - RED_SANDSTONE_STAIRS
        - SANDSTONE_STAIRS
        - SMOOTH_QUARTZ_STAIRS
        - SMOOTH_RED_SANDSTONE_STAIRS
        - SMOOTH_SANDSTONE_STAIRS
        - SPRUCE_STAIRS
        - STONE_BRICK_STAIRS
        - STONE_STAIRS
        - WARPED_STAIRS
        - GRASS_PATH
        - FARMLAND
